### ISSUE TITLE
any chance of updating?

### ISSUE THREAD

**Issue by Dauls** [GryllsAddons/GryllsSwingTimer#1]
for me this is the best swing timer addon even better than sp swing timer imo, sad it doesn't have offhand support

**Comment by GryllsAddons** [comment]
Thanks for your feedback! 

Unfortunately including the offhand in this mod would be a big rewrite of the addon (basically this mod is adding a skin on top of an older version of SP_SwingTimer). 

There are a couple of solutions however!

If you use [ShaguTweaks-mods](https://github.com/GryllsAddons/ShaguTweaks-mods), the "Restyle UI" mod will add a similar style to the SP_SwingTimer.

If you don't then I've uploaded a small [addon](https://github.com/GryllsAddons/SP_StyleTimer) that achieves the same effect.

Once installed the swing timers should look like the image below:

![image](https://github.com/GryllsAddons/SP_StyleTimer/assets/107083057/14514205-7206-43a7-93e6-b606c8609760)

I'll have another look at the styling and see if I can make it closer to the GryllsSwingTimer style!

Hope this helps!

**Comment by Dauls** [comment]
Thanks for your response. 
I tried both but It seems like i have some issues with the sp swing timer and until I resolve them I will continue using GryllsST, anyway I found ShaguTweaksMods to be an incredibly useful addon so thank you again Peace ✌
